const assert=require('node:assert/strict'),F=require('../履约规则.js');
const H=3600000,t=Date.parse('2026-09-11T00:00:00Z');
const rules=F.ensureRules(['finance','accept','ship','pickup','sign','receipt'].map(id=>({id,value:24,warn:80,on:true})));
const o={rules,stock:'stock',lines:[{stock:24,noStock:72}],events:{submittedAt:t},receiptRequired:true};
let s=F.upload({events:{wmsOutboundAt:t-H}},t,{name:'a.pdf'});
assert.equal(F.stage(o,s,'receiptReview',t+H).state,'normal');
assert.equal(F.stage(o,s,'receiptReview',t+25*H).state,'overdue');
assert.throws(()=>F.review(s,'rejected',t+H,''));
s=F.review(s,'rejected',t+H,'回执不清晰');
assert.equal(s.receiptReview,'已驳回');
assert.equal(F.stage(o,s,'receiptReview',t+2*H).end,null);
s=F.upload(s,t+2*H,{name:'b.pdf'});
assert.equal(s.events.firstReceiptUploadedAt,t);
assert.equal(F.stage(o,s,'receiptReview',t+3*H).deadline,t+24*H);
s=F.review(s,'approved',t+3*H);
assert.equal(F.stage(o,s,'receiptReview',t+4*H).state,'completed');
assert.equal(s.reviewHistory.length,2);
assert.equal(F.stage({...o,receiptRequired:false},s,'receiptReview').state,'skipped');
const system={...o,type:'system',customerRule:{receipt:12},arrival:t+10*H};
assert.equal(F.stage(system,s,'receiptReview').deadline,t+24*H);
assert.equal(F.plan(o,t).receiptReview.deadline,F.plan(o,t).receipt.estimated+24*H);
assert.equal(F.plan({...o,receiptRequired:false},t).receiptReview.skipped,true);
assert.equal(F.ensureRules(rules).length,7);
console.log('PASS: receipt review timing, rejection, resubmission, approval, system customers and legacy rules');
