/* 售后时效管理：独立于发货正向履约，复用相同的节点、预警和明细交互。 */
(()=>{
 const KEY='oms-after-sales-sla-v1',H=3600000;
 const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=t=>t?new Date(t).toLocaleString('zh-CN',{hour12:false}).replaceAll('/','-'):'—';
 const now=Date.now();
 const seed=[
  {id:'r202610091538121',orderId:'o202610011325141',customer:'南京万好供应链管理有限公司（好想来）',product:'常温无骨鸡爪 75克 柠檬',amount:55,createdAt:now-2*H,status:'pendingAudit',reason:'客户反馈包装破损',events:{}},
  {id:'r202610091535081',orderId:'o202609281507301',customer:'优仓达超市（万博店）',product:'无骨鸡爪 500克 蒜香',amount:19.5,createdAt:now-8*H,status:'pendingTracking',reason:'商品错发，申请退货',events:{approvedAt:now-5*H}},
  {id:'r202610091533451',orderId:'o202609281507301',customer:'优仓达超市（万博店）',product:'椒麻大杂烩 508克',amount:17,createdAt:now-40*H,status:'inTransit',reason:'临期退货',trackingNo:'SF163820261009',carrier:'顺丰速运',events:{approvedAt:now-36*H,trackingSubmittedAt:now-28*H}},
  {id:'r202610081126301',orderId:'o202609271026181',customer:'杭州嘉客连锁',product:'无骨鸡爪 388克 藤椒',amount:88,createdAt:now-90*H,status:'completed',reason:'包装破损',trackingNo:'JDVA2031886612',carrier:'京东物流',events:{approvedAt:now-87*H,trackingSubmittedAt:now-70*H,warehouseSignedAt:now-12*H}}
 ];
 const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return Array.isArray(v)&&v.length?v:seed}catch{return seed}};
 const save=v=>localStorage.setItem(KEY,JSON.stringify(v));
 let list=read(),tab='all',active=null;
 const rules=[
  {id:'initiate',name:'发起售后',limit:0,help:'售后单创建成功即完成'},
  {id:'audit',name:'售后审核',limit:4,help:'从售后发起开始计时'},
  {id:'tracking',name:'填写退货单号',limit:24,help:'从审核通过开始计时'},
  {id:'warehouse',name:'入库签收',limit:72,help:'从退货单号提交开始计时'}
 ];
 const nav=document.createElement('a');nav.id='navAfterSales';nav.className='sla-nav-item';nav.dataset.group='after-sales';nav.href='#after-sales';nav.innerHTML='<svg class="sla-nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 7h10a4 4 0 0 1 4 4v1M7 7l3-3M7 7l3 3M17 17H7a4 4 0 0 1-4-4v-1m14 5-3-3m3 3-3 3"/></svg><span>售后时效管理</span>';
 const receipt=document.getElementById('navReceipts'),accept=document.getElementById('navAcceptance');(receipt||accept)?.after(nav);
 const oldRender=window.render;window.render=function(){oldRender();if(location.hash==='#after-sales')renderAfterSales();};
 const statusLabel=s=>({pendingAudit:'待审核',auditRejected:'审核驳回',pendingTracking:'待填写单号',inTransit:'待入库签收',completed:'已完成'}[s]||s);
 const currentNode=x=>x.status==='pendingAudit'||x.status==='auditRejected'?'audit':x.status==='pendingTracking'?'tracking':x.status==='inTransit'?'warehouse':'done';
 function deadline(x){const n=currentNode(x);if(n==='audit')return x.createdAt+4*H;if(n==='tracking')return x.events.approvedAt+24*H;if(n==='warehouse')return x.events.trackingSubmittedAt+72*H;return null}
 function level(x){const d=deadline(x);if(!d)return 'done';const left=d-Date.now(),total={audit:4,tracking:24,warehouse:72}[currentNode(x)]*H;return left<=0?'overdue':left<=total*.2?'warning':'normal'}
 function stageCards(){const stages=rules.map(r=>{const rows=list.filter(x=>currentNode(x)===r.id),over=rows.filter(x=>level(x)==='overdue').length,warn=rows.filter(x=>level(x)==='warning').length;return '<button class="after-stage" onclick="afterSalesTab(\''+r.id+'\')"><span class="after-stage-no">'+String(rules.indexOf(r)+1).padStart(2,'0')+'</span><b>'+r.name+'</b><small>'+r.help+'</small><strong>'+rows.length+' <em>单待处理</em></strong><span class="after-stage-counts"><i class="over">超时 '+over+'</i><i class="warn">预警 '+warn+'</i><i>正常 '+Math.max(0,rows.length-over-warn)+'</i></span></button>'}).join('<i class="after-arrow">→</i>');return '<section class="after-flow"><div class="after-section-head"><div><h2>售后时效流程</h2><p>退货类售后按四个节点连续计时；审核驳回后回到申请人修改，不启动填写单号节点。</p></div><button class="btn" onclick="resetAfterSalesDemo()">重置案例</button></div><div class="after-stage-track">'+stages+'</div></section>'}
 function metrics(){const activeRows=list.filter(x=>x.status!=='completed'),over=activeRows.filter(x=>level(x)==='overdue').length,warn=activeRows.filter(x=>level(x)==='warning').length;return '<div class="after-metrics"><button onclick="afterSalesTab(\'active\')"><span>处理中售后</span><b>'+activeRows.length+'</b><small>当前仍有节点待完成</small></button><button class="danger" onclick="afterSalesTab(\'overdue\')"><span>已超时</span><b>'+over+'</b><small>优先跟进责任节点</small></button><button class="caution" onclick="afterSalesTab(\'warning\')"><span>即将超时</span><b>'+warn+'</b><small>进入节点预警区间</small></button><button class="good" onclick="afterSalesTab(\'completed\')"><span>已完成</span><b>'+list.filter(x=>x.status==='completed').length+'</b><small>仓库已完成入库签收</small></button></div>'}
 function visible(x){if(tab==='all')return true;if(tab==='active')return x.status!=='completed';if(tab==='completed')return x.status==='completed';if(tab==='overdue'||tab==='warning')return level(x)===tab;return currentNode(x)===tab}
 function actions(x){if(x.status==='pendingAudit')return '<button class="link-button" onclick="openAfterSales(\''+x.id+'\',\'audit\')">审核</button>';if(x.status==='auditRejected')return '<button class="link-button" onclick="openAfterSales(\''+x.id+'\',\'resubmit\')">修改并重新提交</button>';if(x.status==='pendingTracking')return '<button class="link-button" onclick="openAfterSales(\''+x.id+'\',\'tracking\')">填写退货单号</button>';if(x.status==='inTransit')return '<button class="link-button" onclick="openAfterSales(\''+x.id+'\',\'warehouse\')">确认入库签收</button>';return '<button class="link-button" onclick="openAfterSales(\''+x.id+'\',\'view\')">查看详情</button>'}
 function row(x){const l=level(x),d=deadline(x);return '<tr><td><b>'+esc(x.id)+'</b><small>订单：'+esc(x.orderId)+'</small></td><td><b>'+esc(x.product)+'</b><small>'+esc(x.reason)+'</small></td><td>'+esc(x.customer)+'</td><td>¥ '+Number(x.amount).toFixed(2)+'</td><td>'+fmt(x.createdAt)+'</td><td><span class="after-status '+l+'">'+statusLabel(x.status)+'</span>'+(d?'<small>'+(l==='overdue'?'已超时，截止 ':'节点截止 ')+fmt(d)+'</small>':'<small>流程已完成</small>')+'</td><td>'+actions(x)+'</td></tr>'}
 function renderAfterSales(){document.querySelector('.page-head h1').textContent='售后时效管理';document.querySelector('.page-head p').textContent='从售后发起到仓库入库签收，按节点管理待办、预警、超时和实际完成时间。';document.querySelectorAll('.sla-nav-item').forEach(a=>{a.classList.toggle('active',a===nav);a.removeAttribute('aria-current')});nav.setAttribute('aria-current','page');const rows=list.filter(visible);document.getElementById('content').innerHTML='<div class="after-page">'+metrics()+stageCards()+'<section class="after-list"><div class="after-section-head"><div><h2>售后单明细</h2><p>节点完成记录“实际时间”，未完成节点展示“预计截止”。</p></div><div class="after-tabs">'+[['all','全部'],['audit','待审核'],['tracking','待填写单号'],['warehouse','待入库'],['completed','已完成']].map(v=>'<button class="'+(tab===v[0]?'active':'')+'" onclick="afterSalesTab(\''+v[0]+'\')">'+v[1]+'</button>').join('')+'</div></div><div class="after-table-wrap"><table><thead><tr><th>售后单 / 原订单</th><th>商品 / 原因</th><th>客户名称</th><th>退款金额</th><th>申请时间</th><th>当前节点 / 截止</th><th>操作</th></tr></thead><tbody>'+rows.map(row).join('')+'</tbody></table>'+(rows.length?'':'<p class="empty-orders">暂无符合条件的售后单</p>')+'</div></section></div>'}
 window.afterSalesTab=v=>{tab=v;renderAfterSales()};window.resetAfterSalesDemo=()=>{list=JSON.parse(JSON.stringify(seed));save(list);renderAfterSales();showToast?.('售后案例已重置')};
 function update(id,fn){list=list.map(x=>x.id===id?fn({...x,events:{...x.events}}):x);save(list);renderAfterSales()}
 function flow(x){const items=[['发起售后',x.createdAt,true],['售后审核',x.events.approvedAt,x.status!=='pendingAudit'&&x.status!=='auditRejected'],['填写退货单号',x.events.trackingSubmittedAt,['inTransit','completed'].includes(x.status)],['入库签收',x.events.warehouseSignedAt,x.status==='completed']];return '<div class="after-detail-flow">'+items.map((v,i)=>'<div class="'+(v[2]?'done':'pending')+'"><i>'+(v[2]?'✓':i+1)+'</i><b>'+v[0]+'</b><span>'+(v[2]?'实际 '+fmt(v[1]):'预计 '+fmt(i===1?x.createdAt+4*H:i===2?(x.events.approvedAt?x.events.approvedAt+24*H:null):(x.events.trackingSubmittedAt?x.events.trackingSubmittedAt+72*H:null)))+'</span></div>').join('<em>→</em>')+'</div>'}
 window.openAfterSales=(id,mode)=>{active=id;const x=list.find(v=>v.id===id);let d=document.getElementById('afterSalesDialog');if(!d){d=document.createElement('dialog');d.id='afterSalesDialog';d.className='after-dialog';document.body.append(d)}let form='';if(mode==='audit')form='<div class="after-form"><label>审核意见<textarea id="afterAuditNote" placeholder="通过可选填；驳回时必须填写原因"></textarea></label><div class="after-dialog-actions"><button class="btn danger" onclick="rejectAfterSales()">审核驳回</button><button class="btn primary" onclick="approveAfterSales()">审核通过</button></div></div>';else if(mode==='resubmit')form='<div class="after-form"><p class="after-reject-note">上次驳回原因：'+esc(x.rejectReason)+'</p><label>补充说明<textarea id="afterResubmitNote" placeholder="填写修改说明后重新提交"></textarea></label><div class="after-dialog-actions"><button class="btn primary" onclick="resubmitAfterSales()">重新提交审核</button></div></div>';else if(mode==='tracking')form='<div class="after-form two"><label>物流公司<input id="afterCarrier" placeholder="请输入物流公司"></label><label>退货快递单号<input id="afterTracking" placeholder="请输入退货快递单号"></label><div class="after-dialog-actions"><button class="btn primary" onclick="submitAfterTracking()">确认提交</button></div></div>';else if(mode==='warehouse')form='<div class="after-form two"><label>实际入库时间<input id="afterWarehouseAt" type="datetime-local"></label><label>入库备注<input id="afterWarehouseNote" placeholder="可填写数量差异或异常说明"></label><div class="after-dialog-actions"><button class="btn primary" onclick="signAfterWarehouse()">确认入库签收</button></div></div>';d.innerHTML='<div class="dialog-head"><div><h2>售后单详情</h2><p>'+esc(x.id)+' · '+esc(x.customer)+'</p></div><button class="btn" onclick="this.closest(\'dialog\').close()">关闭</button></div><div class="after-dialog-body">'+flow(x)+'<div class="after-facts"><span>原订单<b>'+esc(x.orderId)+'</b></span><span>商品<b>'+esc(x.product)+'</b></span><span>售后原因<b>'+esc(x.reason)+'</b></span><span>退款金额<b>¥ '+Number(x.amount).toFixed(2)+'</b></span>'+(x.trackingNo?'<span>退货物流<b>'+esc(x.carrier)+' '+esc(x.trackingNo)+'</b></span>':'')+'</div>'+form+'<p id="afterSalesError" class="error" role="alert"></p></div>';if(!d.open)d.showModal()};
 const error=e=>document.getElementById('afterSalesError').textContent=e;
 window.approveAfterSales=()=>{update(active,x=>({...x,status:'pendingTracking',events:{...x.events,approvedAt:Date.now()}}));document.getElementById('afterSalesDialog').close();showToast?.('审核通过，已进入待填写退货单号')};
 window.rejectAfterSales=()=>{const reason=document.getElementById('afterAuditNote').value.trim();if(!reason)return error('审核驳回必须填写原因。');update(active,x=>({...x,status:'auditRejected',rejectReason:reason,events:{...x.events,rejectedAt:Date.now()}}));document.getElementById('afterSalesDialog').close();showToast?.('已驳回，等待申请人修改')};
 window.resubmitAfterSales=()=>{const note=document.getElementById('afterResubmitNote').value.trim();if(!note)return error('请填写修改说明。');update(active,x=>({...x,status:'pendingAudit',resubmitNote:note,rejectReason:null,createdAt:Date.now()}));document.getElementById('afterSalesDialog').close();showToast?.('已重新提交审核')};
 window.submitAfterTracking=()=>{const carrier=document.getElementById('afterCarrier').value.trim(),no=document.getElementById('afterTracking').value.trim();if(!carrier||!no)return error('物流公司和退货快递单号均为必填。');update(active,x=>({...x,status:'inTransit',carrier,trackingNo:no,events:{...x.events,trackingSubmittedAt:Date.now()}}));document.getElementById('afterSalesDialog').close();showToast?.('退货单号已提交')};
 window.signAfterWarehouse=()=>{const input=document.getElementById('afterWarehouseAt').value;if(!input)return error('请选择实际入库时间。');const time=new Date(input).getTime();if(!Number.isFinite(time)||time>Date.now()+5*60000)return error('实际入库时间不能晚于当前时间。');update(active,x=>({...x,status:'completed',warehouseNote:document.getElementById('afterWarehouseNote').value.trim(),events:{...x.events,warehouseSignedAt:time}}));document.getElementById('afterSalesDialog').close();showToast?.('入库签收完成，售后时效流程已结束')};
 window.addEventListener('hashchange',()=>{if(location.hash==='#after-sales')renderAfterSales()});if(location.hash==='#after-sales')setTimeout(renderAfterSales);
})();
