/* Receipt list shares shipment records and review events with the fulfillment board. */
(() => {
 let nav=document.getElementById('navReceipts');
 if(!nav){nav=document.createElement('a');nav.id='navReceipts';nav.className='sla-nav-item';nav.href='#receipts';nav.innerHTML='<svg class="sla-nav-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></svg><span>回执单列表</span>';document.getElementById('navAcceptance').after(nav);}
 let tab='全部',filters={},page=1,size=10,selected=new Set();const esc=v=>safe(v??'—');
 const status=s=>s?(s.receiptReview==='已驳回'?'审核驳回':s.receiptReview||'未上传'):'未上传';
 function rows(){const db=receiptStore.read(),out=[];for(const [id,p] of Object.entries(omsProfiles)){const list=Object.values(db.shipments).filter(s=>s.lines.some(l=>l.orderId===id));if(!list.length&&!(p.statuses||[]).some(v=>v[1]==='已发货'))continue;for(const s of list.length?list:[null]){const original=Object.values(nodeOrders).flat().find(o=>o[0]===id);out.push({key:id+'|'+(s?.id||''),id,p,s,customer:original?.[1]||p.customer||'—'});}}return out;}
 const multiple=(text,value)=>!text||text.split(/[,，\s]+/).filter(Boolean).some(q=>value.includes(q));
 function filtered(){return rows().filter(r=>multiple(filters.order,r.id)&&multiple(filters.shipment,r.s?.id||'')&&(!filters.customer||r.customer.includes(filters.customer))&&(!filters.tracking||(r.s?.trackingNumber||'').includes(filters.tracking))&&(!filters.category||r.p.customerCategory===filters.category)&&(!filters.upload||(filters.upload==='yes')===!!r.s?.receipts?.length)&&(!filters.correct||(filters.correct==='yes')===((r.s?.receipts?.length||0)>1))&&(!filters.start||r.p.createdAt?.slice(0,10)>=filters.start)&&(!filters.end||r.p.createdAt?.slice(0,10)<=filters.end));}
 const oldRender=render;render=function(){oldRender();if(location.hash==='#receipts')draw();};
 function draw(){document.querySelector('.page-head h1').textContent='回执单列表';document.querySelector('.page-head p').textContent='客服直接上传回执单，审核人员完成审核；审核结果同步履约节点。';document.querySelectorAll('.sla-nav-item').forEach(a=>{a.classList.toggle('active',a===nav);a.removeAttribute('aria-current');});nav.setAttribute('aria-current','page');
 const all=filtered(),list=all.filter(r=>tab==='全部'||status(r.s)===tab),pages=Math.max(1,Math.ceil(list.length/size));page=Math.min(page,pages);
 const input=(name,title,placeholder='')=>'<label>'+title+'<input name="'+name+'" value="'+esc(filters[name]||'')+'" placeholder="'+placeholder+'"></label>';
 const select=(name,title,opts)=>'<label>'+title+'<select name="'+name+'"><option value="">全部</option>'+opts.map(([v,t])=>'<option value="'+esc(v)+'" '+(filters[name]===v?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select></label>';
 document.getElementById('content').innerHTML='<section class="receipt-panel"><form id="receiptSearch" class="receipt-search">'+input('order','订单编号','多个订单号以逗号隔开')+input('customer','客户名称','请输入客户名称')+select('correct','是否更正',[['yes','是'],['no','否']])+input('tracking','物流单号','请输入物流单号')+input('shipment','发货单号','多个发货单号以逗号隔开')+'<label>创建时间<div class="receipt-dates"><input aria-label="开始日期" type="date" name="start" value="'+esc(filters.start||'')+'"><input aria-label="结束日期" type="date" name="end" value="'+esc(filters.end||'')+'"></div></label>'+select('category','客户类别',[...new Set(rows().map(r=>r.p.customerCategory).filter(Boolean))].map(v=>[v,v]))+select('upload','是否上传回执',[['no','未上传'],['yes','已上传']])+'<div class="receipt-search-actions"><button class="btn primary">搜索</button><button class="btn" type="reset">重置</button><button class="btn" type="button" id="receiptExport">导出</button><button class="btn" type="button" id="receiptDownload">下载回执文件</button></div></form></section><section class="receipt-panel"><div class="filter-tabs" id="receiptTabs">'+['全部','待审核','审核通过','审核驳回'].map(t=>'<button data-tab="'+t+'" class="'+(tab===t?'active':'')+'">'+t+' '+all.filter(r=>t==='全部'||status(r.s)===t).length+'</button>').join('')+'</div><p class="sub">客服上传回执单后进入待审核；审核驳回后可补传，更正不重置首次上传时间。</p><div class="receipt-table-wrap"><table class="receipt-table"><thead><tr><th><input type="checkbox" id="receiptSelectAll" aria-label="选择本页"></th>'+['订单编号','发货单号','客户名称','收货人','收货地址','订单类型','订单状态','物流单号','审核状态','更正状态','操作'].map(t=>'<th>'+t+'</th>').join('')+'</tr></thead><tbody>'+list.slice((page-1)*size,page*size).map(r=>'<tr><td><input type="checkbox" data-key="'+esc(r.key)+'" aria-label="选择 '+esc(r.id)+'" '+(selected.has(r.key)?'checked':'')+'></td>'+[r.id,r.s?.receiptOnly?'—':r.s?.id,r.customer,r.p.receiver,r.p.address,r.p.type,(r.p.statuses||[]).find(v=>v[0].includes('单状态'))?.[1],r.s?.trackingNumber,status(r.s),(r.s?.receipts?.length||0)>1?'是':'否'].map(v=>'<td title="'+esc(v)+'">'+esc(v)+'</td>').join('')+'<td><button class="orders-toggle" data-action="upload" data-key="'+esc(r.key)+'">上传回执单</button> <button class="orders-toggle" data-action="audit" data-key="'+esc(r.key)+'">审核</button></td></tr>').join('')+(list.length?'':'<tr><td colspan="12" class="empty-orders">暂无符合条件的回执单</td></tr>')+'</tbody></table></div><div class="receipt-pagination"><span>共 '+list.length+' 条</span><select id="receiptSize" aria-label="每页条数">'+[10,20,50].map(n=>'<option '+(size===n?'selected':'')+' value="'+n+'">'+n+'条/页</option>').join('')+'</select><button class="btn" id="receiptPrev" '+(page===1?'disabled':'')+'>上一页</button><span>'+page+' / '+pages+'</span><button class="btn" id="receiptNext" '+(page===pages?'disabled':'')+'>下一页</button></div></section>';
 document.getElementById('receiptSearch').onsubmit=e=>{e.preventDefault();filters=Object.fromEntries(new FormData(e.target));page=1;selected.clear();draw();};document.getElementById('receiptSearch').onreset=()=>{filters={};page=1;selected.clear();draw();};
 document.getElementById('receiptTabs').onclick=e=>{if(e.target.dataset.tab){tab=e.target.dataset.tab;page=1;selected.clear();draw();}};
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openReceipt(b.dataset.key,b.dataset.action));
 document.querySelectorAll('[data-key][type=checkbox]').forEach(c=>c.onchange=()=>c.checked?selected.add(c.dataset.key):selected.delete(c.dataset.key));document.getElementById('receiptSelectAll').onchange=e=>{document.querySelectorAll('[data-key][type=checkbox]').forEach(c=>{c.checked=e.target.checked;c.onchange();});};
 document.getElementById('receiptPrev').onclick=()=>{page--;draw();};document.getElementById('receiptNext').onclick=()=>{page++;draw();};document.getElementById('receiptSize').onchange=e=>{size=+e.target.value;page=1;draw();};
 document.getElementById('receiptExport').onclick=()=>{const values=[['订单编号','发货单号','客户名称','物流单号','审核状态'],...list.filter(r=>!selected.size||selected.has(r.key)).map(r=>[r.id,r.s?.id,r.customer,r.s?.trackingNumber,status(r.s)])];download(URL.createObjectURL(new Blob(['\ufeff'+values.map(v=>v.map(x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})),'回执单列表.csv',true);};
 document.getElementById('receiptDownload').onclick=()=>{const files=list.filter(r=>selected.has(r.key)&&r.s?.receipts?.length);if(!files.length)return showToast('请勾选已上传回执的记录');const seen=new Set();files.forEach(r=>{if(seen.has(r.s.id))return;seen.add(r.s.id);const f=r.s.receipts.at(-1);download(f.data,r.s.id+'-'+f.name);});};
 }
 function download(url,name,revoke=false){const a=document.createElement('a');a.href=url;a.download=name;a.click();if(revoke)setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function openReceipt(key,action){let r=rows().find(r=>r.key===key);if(!r)return;if(!r.s){const receiptId=receiptStore.ensure(r.id);draw();r=rows().find(item=>item.id===r.id&&item.s?.id===receiptId);if(!r)return;key=r.key;}
 let d=document.getElementById('receiptDialog');if(!d){d=document.createElement('dialog');d.id='receiptDialog';d.className='acceptance-dialog receipt-dialog';document.body.append(d);}const s=r.s,file=s.receipts?.at(-1);
 d.innerHTML='<div class="dialog-head"><h2>回执单 · '+esc(s.id)+'</h2><button class="btn" id="receiptClose">关闭</button></div><p>订单：'+esc(r.id)+' · '+esc(status(s))+'</p><p>首次上传：'+esc(s.events?.firstReceiptUploadedAt?kaDate(s.events.firstReceiptUploadedAt):'未上传')+'</p>'+(file?(/\.(png|jpe?g)$/i.test(file.name)?'<img class="receipt-image" src="'+esc(file.data)+'" alt="回执单">':'<p>回执文件：'+esc(file.name)+'</p>')+'<button class="btn" id="receiptFile">下载查看回执</button>':'<p class="empty-orders">尚未上传回执</p>')+'<label class="receipt-upload">上传 / 补传回执<input id="receiptUpload" type="file" accept=".pdf,.png,.jpg,.jpeg"></label><label class="receipt-note">回执备注<textarea id="receiptNote">'+esc(s.receiptNote||'')+'</textarea></label><button class="btn" id="receiptSaveNote">保存备注</button>'+(status(s)==='待审核'?'<label class="receipt-note">审核意见<textarea id="receiptReason" placeholder="驳回时必须填写原因"></textarea></label><button class="btn primary" id="receiptApprove">审核通过</button> <button class="btn" id="receiptReject">驳回补传</button>':'')+'<p id="receiptMessage" role="status"></p><h3>审核记录</h3>'+(s.reviewHistory||[]).map(h=>'<p>'+esc(kaDate(h.time))+' · '+(h.decision==='approved'?'审核通过':'审核驳回')+' · '+esc(h.reason||'—')+'</p>').join('');
 d.querySelector('#receiptClose').onclick=()=>d.close();if(file)d.querySelector('#receiptFile').onclick=()=>download(file.data,file.name);
 const message=t=>d.querySelector('#receiptMessage').textContent=t;
 d.querySelector('#receiptSaveNote').onclick=()=>{try{const note=d.querySelector('#receiptNote').value;receiptStore.save(s.id,x=>({...x,receiptNote:note}));message('备注已保存');}catch(e){message(e.message);}};
 d.querySelector('#receiptUpload').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(!/\.(pdf|png|jpe?g)$/i.test(f.name)||!f.size||f.size>2*1024*1024)throw Error('请选择不超过 2MB 的 PDF、PNG 或 JPG');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('读取失败'));reader.readAsDataURL(f);});receiptStore.save(s.id,x=>Fulfillment.upload(x,new Date().toISOString(),{name:f.name,data}));openReceipt(key,'view');}catch(e){message(e.message);}};
 for(const [id,decision] of [['receiptApprove','approved'],['receiptReject','rejected']]){const b=d.querySelector('#'+id);if(b)b.onclick=()=>{try{receiptStore.save(s.id,x=>Fulfillment.review(x,decision,new Date().toISOString(),d.querySelector('#receiptReason').value));openReceipt(key,'view');}catch(e){message(e.message);}};}
 if(!d.open)d.showModal();if(action==='upload')d.querySelector('#receiptUpload').click();if(action==='audit'&&status(s)!=='待审核')message(s.receipts?.length?'当前回执无需审核或已完成审核。':'请先上传回执单，再进行审核。');
 }
 const oldOpenNode=openNode;openNode=function(id,...args){if(id==='receiptReview'){tab='待审核';page=1;location.hash='#receipts';render();return;}oldOpenNode(id,...args);};
 render();
})();
