export const STORAGE_KEY = "boneless-man-site-config-v1";

const productFieldDefaults = {
  standardName: "",
  shortName: "",
  skuCode: "",
  version: "v1",
  operationStatus: "运行中",
  brand: "脱骨侠",
  flavor: "",
  unit: "袋",
  weight: "",
  boneContent: "",
  storageCondition: "常温",
  solidContent: "100%",
  shelfLife: "",
  spiciness: "无区分",
  salesChannel: "常温休食",
  barcode: "",
  inStockLeadHours: "72",
  outOfStockLeadHours: "216",
  effectImage: "",
};

export const defaultConfig = {
  siteName: "脱骨侠官网",
  desktopWidthPercent: 83.333,
  desktopMaxWidth: 1600,
  header: {
    enabled: true,
    sticky: true,
    logoText: "脱骨侠",
    logoImage: "",
    navigation: [
      { id: "nav-home", label: "首页", link: "#home", enabled: true, children: [] },
      {
        id: "nav-brand",
        label: "品牌产品",
        link: "#brand",
        enabled: true,
        children: [
          { id: "nav-brand-about", label: "品牌介绍", link: "#brand", enabled: true },
          { id: "nav-brand-products", label: "产品系列", link: "#brand", enabled: true },
        ],
      },
      { id: "nav-supply", label: "全供应链", link: "#supply-chain", enabled: true, children: [] },
      { id: "nav-about", label: "关于我们", link: "#about", enabled: true, children: [] },
      {
        id: "nav-news",
        label: "新闻资讯",
        link: "#news",
        enabled: true,
        children: [
          { id: "nav-news-brand", label: "品牌新闻", link: "#news", enabled: true },
          { id: "nav-news-industry", label: "行业动态", link: "#news", enabled: true },
        ],
      },
      { id: "nav-careers", label: "加入我们", link: "#careers", enabled: true, children: [] },
    ],
  },
  footer: {
    enabled: true,
    logoText: "脱骨侠",
    logoImage: "",
    description: "专注鸡爪食品研发、生产与品牌运营，为消费者带来更丰富的美味体验。",
    copyright: "© 2026 安徽卓希食品有限公司 版权所有",
    filingText: "皖ICP备XXXXXXXX号",
    filingLink: "https://beian.miit.gov.cn/",
    securityFilingText: "皖公网安备 XXXXXXXXXXXXXX号",
    securityFilingLink: "",
    navigation: [
      { id: "footer-brand", label: "品牌&产品", link: "", enabled: true, children: [
        { id: "footer-brand-intro", label: "脱骨侠品牌简介", link: "#brand", enabled: true },
        { id: "footer-brand-history", label: "发展里程碑", link: "#brand", enabled: true },
        { id: "footer-brand-honor", label: "品牌荣誉", link: "#brand", enabled: true },
        { id: "footer-product-1", label: "无骨系列", link: "#brand", enabled: true },
        { id: "footer-product-2", label: "虎皮系列", link: "#brand", enabled: true },
        { id: "footer-product-3", label: "低味系列", link: "#brand", enabled: true },
        { id: "footer-product-4", label: "老卤系列", link: "#brand", enabled: true },
        { id: "footer-product-5", label: "盐焗系列", link: "#brand", enabled: true },
        { id: "footer-product-6", label: "泡椒系列", link: "#brand", enabled: true },
        { id: "footer-product-7", label: "椒麻系列", link: "#brand", enabled: true },
        { id: "footer-product-other", label: "其他", link: "#brand", enabled: true },
      ] },
      { id: "footer-supply", label: "全供应链", link: "", enabled: true, children: [
        { id: "footer-supply-factory", label: "工厂布局", link: "#supply-chain", enabled: true },
        { id: "footer-supply-material", label: "原料采购", link: "#supply-chain", enabled: true },
        { id: "footer-supply-production", label: "智能工厂", link: "#supply-chain", enabled: true },
        { id: "footer-supply-rd", label: "研发团队", link: "#supply-chain", enabled: true },
        { id: "footer-supply-quality", label: "品控体系", link: "#supply-chain", enabled: true },
      ] },
      { id: "footer-about", label: "关于我们", link: "", enabled: true, children: [
        { id: "footer-about-company", label: "卓希集团简介", link: "#about", enabled: true },
        { id: "footer-about-culture", label: "企业文化", link: "#about", enabled: true },
      ] },
      { id: "footer-news", label: "新闻资讯", link: "", enabled: true, children: [
        { id: "footer-news-company", label: "卓希新事", link: "#news", enabled: true },
        { id: "footer-news-industry", label: "行业动态", link: "#news", enabled: true },
      ] },
      { id: "footer-careers", label: "加入我们", link: "", enabled: true, children: [
        { id: "footer-careers-channel", label: "渠道分布", link: "#careers", enabled: true },
        { id: "footer-careers-business", label: "业务洽谈", link: "#careers", enabled: true },
        { id: "footer-careers-talent", label: "人才招聘", link: "#careers", enabled: true },
      ] },
      { id: "footer-overseas", label: "海外布局", link: "", enabled: true, children: [
        { id: "footer-overseas-vietnam", label: "越南公司", link: "#about", enabled: true },
      ] },
    ],
  },
  mediaAssets: [],
  pages: [
    {
      id: "home",
      label: "首页",
      title: "脱骨侠官网首页",
      image: "/assets/home.jpg",
      bannerImage: "",
      bannerAlt: "脱骨侠品牌主视觉",
      footerCropPercent: 11.5,
      description: "品牌主视觉、品牌简介、企业实力、资讯和业务洽谈。",
      enabled: true,
    },
    {
      id: "brand",
      label: "品牌产品",
      title: "脱骨侠品牌产品",
      image: "/assets/brand.jpg",
      bannerImage: "",
      bannerAlt: "脱骨侠品牌产品",
      description: "品牌介绍、发展历程、品牌荣誉和全系列产品展示。",
      enabled: true,
    },
    {
      id: "supply-chain",
      label: "全供应链",
      title: "脱骨侠全供应链",
      image: "/assets/supply-chain.jpg",
      bannerImage: "",
      bannerAlt: "脱骨侠全供应链",
      description: "工厂布局、原料精选、智能生产、经营数据和资质证书。",
      enabled: true,
    },
    {
      id: "about",
      label: "关于我们",
      title: "关于脱骨侠",
      image: "/assets/about.jpg",
      bannerImage: "",
      bannerAlt: "关于脱骨侠",
      description: "集团简介、企业文化、研发与生产能力。",
      enabled: true,
    },
    {
      id: "news",
      label: "新闻资讯",
      title: "脱骨侠新闻资讯",
      image: "/assets/news.jpg",
      bannerImage: "",
      bannerAlt: "脱骨侠新闻资讯",
      description: "品牌新闻、卓希新事和行业动态。",
      enabled: true,
    },
    {
      id: "careers",
      label: "加入我们",
      title: "加入脱骨侠",
      image: "/assets/careers.jpg",
      bannerImage: "",
      bannerAlt: "加入脱骨侠",
      description: "渠道分布、业务合作和人才招聘信息。",
      enabled: true,
    },
  ],
  introductions: {
    brand: {
      id: "brand",
      label: "品牌简介",
      eyebrow: "Brand story",
      title: "专注好吃的鸡爪食品",
      subtitle: "脱骨侠品牌简介",
      summary: "脱骨侠专注鸡爪休闲食品研发与创新，以更丰富的风味和更轻松的食用体验，让美味进入更多日常场景。",
      content: "从一只鸡爪出发，我们持续探索原料、工艺、口味与包装的更多可能。\n\n品牌坚持年轻化表达与稳定品质并重，为消费者提供多系列、多规格的鸡爪食品选择。",
      image: "/assets/products/food-1.png",
      enabled: true,
    },
    group: {
      id: "group",
      label: "集团介绍",
      eyebrow: "About Zhuoxi",
      title: "安徽卓希食品有限公司",
      subtitle: "卓希集团介绍",
      summary: "卓希是一家集食品研发、生产、供应链管理与品牌运营于一体的现代化食品企业。",
      content: "公司围绕消费者需求持续完善产品研发、智能生产、品质管理与渠道服务能力。\n\n通过稳定的供应链体系和专业团队，卓希不断推动休闲食品产业升级，为合作伙伴与消费者创造长期价值。",
      image: "/assets/about.jpg",
      enabled: true,
    },
  },
  contentSections: {
    about: [
      {
        id: "capabilities",
        label: "生产研发品控",
        eyebrow: "Core capabilities",
        title: "生产中心、研发中心与品控体系",
        summary: "覆盖生产制造、新品研发与食品安全管理的综合能力体系。",
        content: "生产中心拥有智能化生产与原料加工能力；研发中心聚焦风味、工艺与产品创新；品控体系贯穿原料、生产和成品检验全过程。",
        image: "/assets/content/lab-research.png",
        secondaryImage: "/assets/content/quality-control.png",
        items: [
          { value: "30+", label: "研发人员" },
          { value: "45项", label: "发明专利" },
          { value: "90000㎡", label: "生产研发场地" },
        ],
        enabled: true,
      },
      {
        id: "milestones",
        label: "发展里程碑",
        eyebrow: "Development milestone",
        title: "发展里程碑",
        summary: "记录企业和品牌的重要成长节点。",
        content: "通过持续的产品创新、渠道拓展与供应链建设，卓希稳步推进品牌发展。",
        image: "",
        secondaryImage: "",
        items: [
          { value: "2020.6", label: "品牌与业务体系启动" },
          { value: "2022.12", label: "核心产品持续升级" },
          { value: "2023.12", label: "销量与渠道取得新突破" },
          { value: "2024.6", label: "工厂和研发能力进一步完善" },
        ],
        enabled: true,
      },
      {
        id: "honors",
        label: "品牌荣誉",
        eyebrow: "Brand honors",
        title: "品牌荣誉",
        summary: "品牌、产品和团队获得的代表性奖项与行业认可。",
        content: "荣誉见证成长，也推动我们持续提升产品品质与品牌体验。",
        image: "",
        secondaryImage: "",
        items: [],
        enabled: true,
      },
      {
        id: "culture",
        label: "卓希文化",
        eyebrow: "Zhuoxi culture",
        title: "原真、专业、长期主义",
        summary: "以真实原料、专业能力和长期价值为企业文化核心。",
        content: "我们尊重食品本味，坚持专业标准，也珍视团队、伙伴与消费者之间长期而稳定的信任。",
        image: "/assets/content/food-production.png",
        secondaryImage: "/assets/content/quality-control.png",
        items: [
          { value: "原真", label: "成为全球领先的鸡爪食品专家" },
        ],
        enabled: true,
      },
    ],
    supply: [
      {
        id: "factory-layout",
        label: "工厂布局",
        eyebrow: "Factory layout",
        title: "工厂布局 迈出国门",
        summary: "围绕核心市场建设稳定、协同的生产与供应网络。",
        content: "鸡爪食品生产工厂规模持续扩展，并结合海外原料与加工资源完善全球化布局。",
        image: "",
        secondaryImage: "",
        items: [
          { value: "90000㎡", label: "超级工厂" },
          { value: "全球", label: "供应链布局" },
        ],
        enabled: true,
      },
      {
        id: "raw-materials",
        label: "原料精选",
        eyebrow: "Raw material sourcing",
        title: "原料精选 源头可靠",
        summary: "从供应商审核、采购到运输，全流程建立可追溯标准。",
        content: "与稳定的原料伙伴协作，通过审核与过程管理保障原料品质和交付稳定。",
        image: "",
        secondaryImage: "",
        items: [],
        enabled: true,
      },
      {
        id: "production-quality",
        label: "生产质检",
        eyebrow: "Production quality",
        title: "把控细节 规范环节",
        summary: "通过自动质检设备和标准化流程，稳定每一批产品品质。",
        content: "质量管理覆盖生产关键控制点，并通过人员、设备和数据的协同持续优化。",
        image: "/assets/content/quality-control.png",
        secondaryImage: "/assets/content/food-production.png",
        items: [],
        enabled: true,
      },
      {
        id: "research-strength",
        label: "研发能力",
        eyebrow: "Research strength",
        title: "食品研究院与多地研发中心",
        summary: "建设多层次研发体系，推动口味、工艺和产品创新快速落地。",
        content: "研发团队围绕消费趋势、原料应用和生产工艺开展协同创新。",
        image: "/assets/content/lab-research.png",
        secondaryImage: "",
        items: [
          { value: "192", label: "研发人员" },
          { value: "3000㎡", label: "研发场地" },
          { value: "100+", label: "研发实验设备" },
        ],
        enabled: true,
      },
      {
        id: "certification",
        label: "品质认证",
        eyebrow: "Quality certification",
        title: "管控严格 品质稳定",
        summary: "以食品安全和质量管理体系认证支撑稳定生产。",
        content: "认证图片、证书名称及相关说明均可在后台持续更新。",
        image: "",
        secondaryImage: "",
        items: [
          { value: "HACCP", label: "食品安全管理" },
          { value: "ISO 9001", label: "质量管理体系" },
          { value: "FSSC 22000", label: "食品安全体系" },
        ],
        enabled: true,
      },
    ],
    careers: [
      {
        id: "channels",
        label: "渠道分布",
        eyebrow: "Channel distribution",
        title: "多平台、多渠道协同覆盖",
        summary: "线上内容电商、综合电商与线下经销体系共同服务消费者。",
        content: "渠道数据、平台说明和覆盖规模均可根据业务进展更新。",
        image: "/assets/content/channel-map.png",
        secondaryImage: "",
        items: [
          { value: "500万", label: "粉丝量级" },
          { value: "300家", label: "经销商" },
          { value: "50家", label: "门店" },
          { value: "75个", label: "KA/CVS系统" },
        ],
        enabled: true,
      },
      {
        id: "business",
        label: "业务洽谈",
        eyebrow: "Business negotiation",
        title: "欢迎加入我们，携手共赢",
        summary: "面向线下区域代理、线上一件代发及其他业务合作。",
        content: "可在此维护合作方向、联系人、联系电话和合作说明。",
        image: "/assets/content/business-cooperation.png",
        secondaryImage: "",
        items: [
          { value: "400-000-0000", label: "业务咨询" },
        ],
        enabled: true,
      },
      {
        id: "talent",
        label: "人才招聘",
        eyebrow: "Talent recruitment",
        title: "与优秀的人一起创造好产品",
        summary: "持续寻找认同食品行业、品牌创新与长期价值的伙伴。",
        content: "招聘热线、联系地址、邮箱和招聘说明可通过后台统一维护。",
        image: "/assets/content/talent-recruitment.png",
        secondaryImage: "",
        items: [
          { value: "400-000-0000", label: "客服热线" },
          { value: "安徽省马鞍山市和县", label: "联系地址" },
          { value: "hr@zhuoxi.com", label: "招聘邮箱" },
        ],
        enabled: true,
      },
    ],
  },
  productCategories: [
    { id: "category-boneless", name: "无骨系列", description: "整只脱骨，爽脆入味，多种风味可选。", detailText: "查看详情", image: "/assets/products/food-1.png", enabled: true, order: 1 },
    { id: "category-tiger-skin", name: "虎皮系列", description: "先炸后卤，软糯入味，一嗦脱骨。", detailText: "查看详情", image: "/assets/products/food-2.png", enabled: true, order: 2 },
    { id: "category-low-flavor", name: "低味系列", description: "复合香辛料入味，口感浓郁有层次。", detailText: "查看详情", image: "/assets/products/food-3.png", enabled: true, order: 3 },
    { id: "category-braised", name: "老卤系列", description: "老汤慢卤，传统风味醇香入骨。", detailText: "查看详情", image: "/assets/products/food-4.png", enabled: true, order: 4 },
    { id: "category-salt-baked", name: "盐焗系列", description: "咸香紧实，保留鸡爪本味与嚼劲。", detailText: "查看详情", image: "/assets/products/food-5.png", enabled: true, order: 5 },
    { id: "category-pickled-pepper", name: "泡椒系列", description: "酸辣清爽，脆嫩开胃。", detailText: "查看详情", image: "/assets/products/food-6.png", enabled: true, order: 6 },
    { id: "category-pepper", name: "椒麻系列", description: "椒香与麻感交织，鲜香上瘾。", detailText: "查看详情", image: "/assets/products/food-7.png", enabled: true, order: 7 },
    { id: "category-korean", name: "韩式系列", description: "甜辣浓郁，软糯有嚼劲。", detailText: "查看详情", image: "/assets/products/food-8.png", enabled: true, order: 8 },
  ],
  products: [
    {
      id: "product-1",
      ...productFieldDefaults,
      categoryId: "category-boneless",
      name: "无骨鸡爪",
      standardName: "无骨鸡爪-脱骨侠-28克-卤香味-10个月（100%-无骨-常温-袋）",
      shortName: "无骨鸡爪-脱骨侠-28克-卤香味-10个月",
      skuCode: "TGX-WG-LX28G10M-CW-N-4U",
      flavor: "卤香",
      weight: "28g",
      boneContent: "无骨",
      shelfLife: "10个月",
      barcode: "6975750070358",
      series: "无骨系列",
      slogan: "整只脱骨 一口爽脆",
      description: "超级单品无骨鸡爪，酸辣鲜香，覆盖多种风味与包装规格。",
      image: "/assets/products/food-1.png",
      packageImage: "/assets/products/package-1.png",
      specs: "盒装 / 袋装 / 罐装",
      salesText: "累计销量100000000+罐",
      actionText: "探索全系列产品",
      link: "#brand",
      featured: true,
      status: "published",
      order: 1,
    },
    {
      id: "product-2",
      ...productFieldDefaults,
      categoryId: "category-tiger-skin",
      name: "虎皮凤爪",
      series: "虎皮系列",
      slogan: "先炸后卤 一嗦脱骨",
      description: "冷吃热吃均可，清爽解腻，鲜香浓郁。",
      image: "/assets/products/food-2.png",
      packageImage: "/assets/products/package-2.png",
      specs: "盒装 / 袋装",
      salesText: "",
      actionText: "探索全系列产品",
      link: "#brand",
      featured: false,
      status: "published",
      order: 2,
    },
    {
      id: "product-3",
      ...productFieldDefaults,
      categoryId: "category-low-flavor",
      name: "低味鸡爪",
      series: "低味系列",
      slogan: "辣的酣畅 吃的过瘾",
      description: "地道低味，名厨手笔，18种香料呈现天然好味。",
      image: "/assets/products/food-3.png",
      packageImage: "/assets/products/package-3.png",
      specs: "盒装",
      salesText: "",
      actionText: "探索全系列产品",
      link: "#brand",
      featured: false,
      status: "published",
      order: 3,
    },
    {
      id: "product-4",
      ...productFieldDefaults,
      categoryId: "category-braised",
      name: "老卤鸡爪",
      series: "老卤系列",
      slogan: "老汤慢卤 醇香入骨",
      description: "草本卤料与天然香辛料，低温慢卤保留传统工艺。",
      image: "/assets/products/food-4.png",
      packageImage: "/assets/products/package-4.png",
      specs: "袋装",
      salesText: "",
      actionText: "探索全系列产品",
      link: "#brand",
      featured: false,
      status: "published",
      order: 4,
    },
    {
      id: "product-5",
      ...productFieldDefaults,
      categoryId: "category-salt-baked",
      name: "盐焗鸡爪",
      series: "盐焗系列",
      slogan: "Q弹咸香 肉质紧实",
      description: "非遗工艺先腌后焗，骨香味浓，层次丰富。",
      image: "/assets/products/food-5.png",
      packageImage: "/assets/products/package-5.png",
      specs: "袋装",
      salesText: "",
      actionText: "探索全系列产品",
      link: "#brand",
      featured: false,
      status: "published",
      order: 5,
    },
    {
      id: "product-6",
      ...productFieldDefaults,
      categoryId: "category-pickled-pepper",
      name: "泡椒凤爪",
      series: "泡椒系列",
      slogan: "酸辣入味 一口爽脆",
      description: "泡椒工艺，酸辣清爽，口感脆嫩。",
      image: "/assets/products/food-6.png",
      packageImage: "/assets/products/package-6.png",
      specs: "袋装",
      salesText: "",
      actionText: "探索全系列产品",
      link: "#brand",
      featured: false,
      status: "published",
      order: 6,
    },
    {
      id: "product-7",
      ...productFieldDefaults,
      categoryId: "category-pepper",
      name: "椒麻大杂烩",
      series: "椒麻系列",
      slogan: "荤素搭配 多种脆感",
      description: "椒麻鲜香，一口上瘾，多种食材搭配。",
      image: "/assets/products/food-7.png",
      packageImage: "/assets/products/package-7.png",
      specs: "盒装",
      salesText: "",
      actionText: "探索全系列产品",
      link: "#brand",
      featured: false,
      status: "published",
      order: 7,
    },
    {
      id: "product-8",
      ...productFieldDefaults,
      categoryId: "category-korean",
      name: "韩式火辣鸡爪",
      series: "韩式系列",
      slogan: "软糯香甜 嚼劲十足",
      description: "椒麻鲜香，软糯有嚼劲，韩式甜辣风味。",
      image: "/assets/products/food-8.png",
      packageImage: "/assets/products/package-8.png",
      specs: "盒装",
      salesText: "",
      actionText: "探索全系列产品",
      link: "#brand",
      featured: false,
      status: "published",
      order: 8,
    },
  ],
  news: [
    {
      id: "news-1",
      title: "“脱骨侠杯”和县英雄联盟竞技大赛圆满收官，峡谷逐梦，青春热血！",
      category: "卓希新事",
      date: "2026-05-04",
      excerpt: "热血铸荣耀，峡谷竞风流！赛事在近日圆满落下帷幕。",
      coverImage: "/assets/news/news-1.png",
      articleId: "article-1",
      featured: true,
      status: "published",
      order: 1,
    },
    {
      id: "news-2",
      title: "开学季破冰，脱骨侠带你认识新朋友",
      category: "卓希新事",
      date: "2026-03-01",
      excerpt: "脱骨侠校园活动走进校园，用美食连接年轻消费者。",
      coverImage: "/assets/news/news-2.png",
      articleId: "article-2",
      featured: false,
      status: "published",
      order: 2,
    },
    {
      id: "news-3",
      title: "头号看球搭子上架！",
      category: "卓希新事",
      date: "2026-06-22",
      excerpt: "脱骨侠全系列产品亮相终端门店，成为观赛休闲新搭配。",
      coverImage: "/assets/news/news-3.png",
      articleId: "article-3",
      featured: false,
      status: "published",
      order: 3,
    },
    {
      id: "news-4",
      title: "世界杯激战正酣，脱骨侠邀您体验精彩瞬间",
      category: "卓希新事",
      date: "2026-06-26",
      excerpt: "线下互动活动火热进行中，打造品牌与消费者的新连接。",
      coverImage: "/assets/news/news-4.png",
      articleId: "article-4",
      featured: false,
      status: "published",
      order: 4,
    },
  ],
  articles: [
    {
      id: "article-1",
      title: "“脱骨侠杯”和县英雄联盟竞技大赛圆满收官",
      slug: "boneless-man-esports-final",
      author: "卓希品牌中心",
      summary: "赛事圆满收官，青年选手以热爱和实力点燃赛场。",
      coverImage: "/assets/news/news-1.png",
      body: "热血铸荣耀，峡谷竞风流！“脱骨侠杯”和县英雄联盟竞技大赛在近日圆满落下帷幕。\n\n本次赛事吸引了众多青年选手参与。经过多轮角逐，参赛队伍以默契配合和精彩操作，为现场观众带来了一场充满青春活力的电竞盛宴。\n\n脱骨侠将继续关注年轻消费者的兴趣场景，通过美食、运动和潮流文化，与更多年轻用户建立真诚连接。",
      seoTitle: "脱骨侠杯电竞大赛圆满收官 | 脱骨侠",
      status: "published",
      updatedAt: "2026-05-04",
    },
    {
      id: "article-2",
      title: "开学季破冰，脱骨侠带你认识新朋友",
      slug: "campus-new-semester-event",
      author: "卓希品牌中心",
      summary: "校园互动活动让新同学在轻松氛围中认识彼此。",
      coverImage: "/assets/news/news-2.png",
      body: "新学期，新同学，也有新的美味陪伴。\n\n脱骨侠走进校园，以趣味互动和产品体验帮助同学们打破陌生感，在分享美食的过程中认识新朋友。\n\n未来，品牌将继续丰富校园场景活动，为年轻消费者带来更多轻松、有趣的体验。",
      seoTitle: "脱骨侠开学季校园活动 | 脱骨侠",
      status: "published",
      updatedAt: "2026-03-01",
    },
    {
      id: "article-3",
      title: "头号看球搭子上架",
      slug: "football-viewing-snack",
      author: "卓希品牌中心",
      summary: "脱骨侠多款鸡爪产品成为看球与聚会场景的新搭配。",
      coverImage: "/assets/news/news-3.png",
      body: "精彩赛事少不了合适的看球搭子。\n\n脱骨侠多款产品已陆续上架终端门店，覆盖酸辣、椒麻、泡椒、盐焗等多种口味，为观赛、聚会和夜宵场景提供更多选择。",
      seoTitle: "脱骨侠头号看球搭子上架 | 脱骨侠",
      status: "published",
      updatedAt: "2026-06-22",
    },
    {
      id: "article-4",
      title: "世界杯激战正酣，脱骨侠邀您体验精彩瞬间",
      slug: "world-cup-offline-event",
      author: "卓希品牌中心",
      summary: "脱骨侠线下互动活动与消费者共享赛事热情。",
      coverImage: "/assets/news/news-4.png",
      body: "世界杯激战正酣，脱骨侠线下互动活动也在火热进行。\n\n品牌通过趣味挑战、产品试吃和现场互动，为消费者打造沉浸式观赛体验，让美味与赛场热情同频。",
      seoTitle: "脱骨侠世界杯线下活动 | 脱骨侠",
      status: "published",
      updatedAt: "2026-06-26",
    },
  ],
};

export function loadConfig() {
  try {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (!saved) return structuredClone(defaultConfig);
    const parsed = JSON.parse(saved);
    return {
      ...structuredClone(defaultConfig),
      ...parsed,
      header: {
        ...structuredClone(defaultConfig.header),
        ...(parsed.header ?? {}),
        navigation: Array.isArray(parsed.header?.navigation)
          ? parsed.header.navigation
          : structuredClone(defaultConfig.header.navigation),
      },
      footer: {
        ...structuredClone(defaultConfig.footer),
        ...(parsed.footer ?? {}),
        navigation: Array.isArray(parsed.footer?.navigation)
          ? parsed.footer.navigation.map((item) => {
              const fallback = defaultConfig.footer.navigation.find((entry) => entry.id === item.id);
              return {
                ...fallback,
                ...item,
                children: Array.isArray(item.children)
                  ? item.children
                  : structuredClone(fallback?.children ?? []),
              };
            })
          : structuredClone(defaultConfig.footer.navigation),
      },
      pages: Array.isArray(parsed.pages)
        ? parsed.pages.map((page) => ({
            ...defaultConfig.pages.find((item) => item.id === page.id),
            ...page,
          }))
        : structuredClone(defaultConfig.pages),
      introductions: {
        ...structuredClone(defaultConfig.introductions),
        ...(parsed.introductions ?? {}),
        brand: {
          ...structuredClone(defaultConfig.introductions.brand),
          ...(parsed.introductions?.brand ?? {}),
        },
        group: {
          ...structuredClone(defaultConfig.introductions.group),
          ...(parsed.introductions?.group ?? {}),
        },
      },
      contentSections: {
        about: Array.isArray(parsed.contentSections?.about)
          ? parsed.contentSections.about
          : structuredClone(defaultConfig.contentSections.about),
        supply: Array.isArray(parsed.contentSections?.supply)
          ? parsed.contentSections.supply
          : structuredClone(defaultConfig.contentSections.supply),
        careers: Array.isArray(parsed.contentSections?.careers)
          ? parsed.contentSections.careers
          : structuredClone(defaultConfig.contentSections.careers),
      },
      productCategories: Array.isArray(parsed.productCategories)
        ? parsed.productCategories.map((category) => {
            const fallback = defaultConfig.productCategories.find((item) => item.id === category.id);
            return {
              ...fallback,
              ...category,
              description: category.description ?? fallback?.description ?? "",
              detailText: category.detailText ?? fallback?.detailText ?? "查看详情",
            };
          })
        : structuredClone(defaultConfig.productCategories),
      products: Array.isArray(parsed.products)
        ? parsed.products.map((product) => {
            const matchingCategory = defaultConfig.productCategories.find(
              (category) => category.name === product.series,
            );
            return {
              ...productFieldDefaults,
              ...product,
              categoryId: product.categoryId ?? matchingCategory?.id ?? "",
            };
          })
        : structuredClone(defaultConfig.products),
      news: Array.isArray(parsed.news)
        ? parsed.news
        : structuredClone(defaultConfig.news),
      articles: Array.isArray(parsed.articles)
        ? parsed.articles
        : structuredClone(defaultConfig.articles),
      mediaAssets: Array.isArray(parsed.mediaAssets)
        ? parsed.mediaAssets
        : structuredClone(defaultConfig.mediaAssets),
    };
  } catch {
    return structuredClone(defaultConfig);
  }
}

export function saveConfig(config) {
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
}
