from pathlib import Path
p=Path('C:/Users/admin/.codex/visualizations/2026/10/07/01a113f3-1f33-7d40-bf39-7aaed264b0b9/custom-activity.html')
s=p.read_text(encoding='utf-8')
old='<label><span><em>*</em> 执行范围</span><select id="scope"><option>指定系统 / 客户</option><option>指定门店</option><option>指定区域</option></select></label><label class="wide" id="scope-detail">范围说明<input required value="示例连锁系统团购业务"></label>'
new='''<div class="wide"><div><em>*</em> 选择门店 <small id="store-count">已选0家</small></div><div class="row" style="margin-top:12px"><button type="button" class="link" id="choose-stores">＋选择门店</button><button type="button" class="link" id="import-stores">＋导入门店</button><span class="error" style="font-size:12px">说明：1.门店必须唯一。2.再次导入 / 选择时，将替换原有数据，以最新数据为准。</span></div><input hidden type="file" id="store-file" accept=".csv,text/csv"><div id="store-picker" hidden style="margin-top:16px;padding:16px;border:1px solid var(--p-line);border-radius:4px"><div class="muted">选择执行门店（演示门店）</div><div id="store-options" class="row" style="margin:12px 0"></div><div class="row"><button type="button" id="confirm-stores">确认选择并替换</button><button type="button" id="cancel-stores">取消</button></div></div><div id="store-message" role="status" aria-live="polite"></div><div class="table-wrap"><table><thead><tr><th>序号</th><th>门店名称 *</th><th>活动日期</th><th>门店地址</th><th>操作</th></tr></thead><tbody id="store-rows"><tr><td colspan="5" style="text-align:center;color:var(--p-sub)">暂无数据，请选择或导入门店</td></tr></tbody></table></div><small>导入支持UTF-8 CSV，表头：门店编码、门店名称、门店地址。按门店编码去重。</small></div>'''
assert old in s
s=s.replace(old,new).replace('关联商品、门店或原审批单（按需填写）','关联商品或原审批单（按需填写）').replace('<label>门店范围<input placeholder="选择门店或上传清单"></label>','')
s=s.replace("q('#scope').onchange=()=>{q('#scope-detail').firstChild.textContent=q('#scope').value==='指定门店'?'门店范围 / 清单说明':'范围说明'};",'')
s=s.replace("else if(!rows.length)msg=", "else if(!stores.length){msg='请至少选择或导入一家执行门店。';target=q('#choose-stores')}else if(!rows.length)msg=")
insert='''let stores=[];const catalog=[{code:'DEMO001',name:'示例门店 · 中心店',address:'上海市示例路1号'},{code:'DEMO002',name:'示例门店 · 城东店',address:'上海市示例路2号'},{code:'DEMO003',name:'示例门店 · 城西店',address:'上海市示例路3号'}];
function storeDraw(){const tb=q('#store-rows');tb.replaceChildren();q('#store-count').textContent='已选'+stores.length+'家';if(!stores.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.style.textAlign='center';td.textContent='暂无数据，请选择或导入门店';tr.append(td);tb.append(tr)}stores.forEach((st,i)=>{const tr=document.createElement('tr');[String(i+1),st.name,q('#start').value+' 至 '+q('#end').value,st.address].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});const td=document.createElement('td'),b=document.createElement('button');b.type='button';b.className='delete';b.textContent='删除';b.setAttribute('aria-label','删除'+st.name);b.onclick=()=>{stores.splice(i,1);storeDraw()};td.append(b);tr.append(td);tb.append(tr)})}
q('#choose-stores').onclick=()=>{q('#store-picker').hidden=false;const opts=q('#store-options');opts.replaceChildren();catalog.forEach(st=>{const label=document.createElement('label');label.className='check';const cb=document.createElement('input');cb.type='checkbox';cb.value=st.code;cb.checked=stores.some(v=>v.code===st.code);label.append(cb,document.createTextNode(st.name));opts.append(label)})};q('#cancel-stores').onclick=()=>{q('#store-picker').hidden=true};q('#confirm-stores').onclick=()=>{const codes=Array.from(q('#store-options').querySelectorAll('input:checked')).map(el=>el.value);if(!codes.length){q('#store-message').textContent='请至少勾选一家门店，原有数据已保留。';return}stores=catalog.filter(st=>codes.includes(st.code));storeDraw();q('#store-picker').hidden=true;q('#store-message').textContent='已更新执行门店，共'+stores.length+'家。'};
function parseCSV(text){const all=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\\n'||c==='\\r')&&!quoted){if(c==='\\r'&&text[i+1]==='\\n')i++;row.push(cell);if(row.some(v=>v.trim()))all.push(row);row=[];cell=''}else cell+=c}if(quoted)throw Error('CSV引号未闭合');row.push(cell);if(row.some(v=>v.trim()))all.push(row);return all}
q('#import-stores').onclick=()=>q('#store-file').click();q('#store-file').onchange=async()=>{const file=q('#store-file').files[0];if(!file)return;try{const data=parseCSV((await file.text()).replace(/^\\uFEFF/,''));const h=(data.shift()||[]).map(v=>v.trim()),ci=h.indexOf('门店编码'),ni=h.indexOf('门店名称'),ai=h.indexOf('门店地址');if(ci<0||ni<0||ai<0)throw Error('缺少表头：门店编码、门店名称、门店地址');const map=new Map();let duplicate=0;data.forEach((row,i)=>{const st={code:(row[ci]||'').trim(),name:(row[ni]||'').trim(),address:(row[ai]||'').trim()};if(!st.code||!st.name||!st.address)throw Error('第'+(i+2)+'行有必填内容缺失');if(map.has(st.code))duplicate++;map.set(st.code,st)});if(!map.size)throw Error('文件没有门店数据');stores=Array.from(map.values());storeDraw();q('#store-picker').hidden=true;q('#store-message').textContent='导入成功，共'+stores.length+'家门店'+(duplicate?'，已合并'+duplicate+'条重复编码（保留最后一条）。':'。')}catch(e){q('#store-message').textContent='导入失败：'+e.message+'。请修正后重试，原有门店已保留。'}finally{q('#store-file').value=''}};q('#start').addEventListener('change',storeDraw);q('#end').addEventListener('change',storeDraw);
'''
s=s.replace("q('#add').onclick=",insert+"q('#add').onclick=")
p.write_text(s,encoding='utf-8')
