const{chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('file:///E:/cxy/09-设计与原型/计划发货管理-交互原型.html');await page.evaluate(()=>{state=seed();state.couriers=defaultCouriers();save();render()});
await page.getByRole('button',{name:'新建发货计划'}).click();
for(let id of ['SO-001','SO-002'])await page.locator('#modalBody label').filter({hasText:id}).locator('input').check();
await page.getByRole('button',{name:'下一步',exact:true}).click();await page.getByRole('button',{name:'下一步',exact:true}).click();await page.getByRole('button',{name:'下一步',exact:true}).click();
await page.getByRole('button',{name:'确认并同步旺店通',exact:true}).click();
assert.match(await page.locator('#modalTitle').innerText(),/同步旺店通/);assert.equal(await page.locator('#modalBody tbody tr').count(),2);
await page.locator('#modalBody summary').click();await page.locator('#syncOutcome').selectOption('mixed');await page.getByRole('button',{name:'确认同步',exact:true}).click();
await page.waitForFunction(()=>!busy);let p=await page.evaluate(()=>state.plans[0]);assert.equal(p.sync,'partial');assert.equal(p.syncResults[0].status,'success');assert.equal(p.syncResults[1].status,'failed');let firstWdt=p.syncResults[0].wdt;
await page.getByRole('button',{name:'修复映射并重试失败订单（演示）',exact:true}).click();assert.equal(await page.locator('#modalBody tbody tr').count(),1);await page.getByRole('button',{name:'确认同步',exact:true}).click();await page.waitForFunction(()=>!busy);
p=await page.evaluate(()=>state.plans[0]);assert.equal(p.sync,'success');assert.equal(p.syncResults[0].wdt,firstWdt);assert.equal(p.syncResults.length,2);
await page.getByRole('button',{name:'返回列表',exact:true}).click();assert.equal(await page.getByRole('checkbox',{name:'选择计划 '+p.id,exact:true}).isDisabled(),true);
await page.evaluate(()=>{let template=state.plans[0];for(let [n,id] of ['SO-004','SO-005'].entries()){let o=state.orders.find(o=>o.id===id);state.plans.unshift({...template,id:'PL-BATCH-'+n,orderIds:[id],customer:o.customer,address:o.address,due:o.due,sync:'none',syncResults:undefined,wdt:'',logs:['演示待同步计划'],shipped:false});o.status='occupied'}render()});
await page.getByRole('checkbox',{name:'选择计划 PL-BATCH-0',exact:true}).check();await page.getByRole('checkbox',{name:'选择计划 PL-BATCH-1',exact:true}).check();await page.getByRole('button',{name:'批量同步旺店通',exact:true}).click();
assert.equal(await page.locator('#modalBody tbody tr').count(),2);await page.getByRole('button',{name:'确认同步',exact:true}).click();await page.waitForFunction(()=>!busy);assert.equal(await page.evaluate(()=>state.plans.filter(p=>p.id.startsWith('PL-BATCH')&&p.sync==='success').length),2);
await page.getByRole('button',{name:'返回列表',exact:true}).click();await page.screenshot({path:'E:/cxy/09-设计与原型/计划发货管理-旺店通同步预览.png',fullPage:true});await page.reload();assert.equal(await page.evaluate(()=>state.plans.filter(p=>p.id.startsWith('PL-BATCH')&&p.sync==='success').length),2);
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
console.log('PASS：确认并同步、同步内容预览、部分订单失败、仅重试失败订单、成功订单不重复创建、单条与批量同步入口、状态持久化、移动端宽度；无浏览器脚本错误。');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
