const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const response=await page.goto('http://127.0.0.1:8765');assert.equal(response.status(),200);
 await page.screenshot({path:'E:/cxy/09-设计与原型/计划发货管理-桌面预览.png',fullPage:true});
 await page.getByRole('button',{name:'订单拆合单'}).click();
 await page.getByRole('checkbox',{name:'选择 SO-001',exact:true}).check();
 await page.getByRole('checkbox',{name:'选择 SO-002',exact:true}).check();
 await page.getByRole('button',{name:'合并订单',exact:true}).click();
 await page.getByRole('button',{name:'确认合并',exact:true}).click();
 let merged=await page.evaluate(()=>state.orders.find(o=>o.id.startsWith('MG-')));
 assert.equal(merged.items[0].qty,40);assert.equal(merged.source,'SO-001 / SO-002');
 await page.getByRole('checkbox',{name:'选择 '+merged.id,exact:true}).check();
 await page.getByRole('button',{name:'拆分订单',exact:true}).click();
 await page.getByRole('button',{name:'确认拆分',exact:true}).click();
 let parts=await page.evaluate(()=>state.orders.filter(o=>o.id.startsWith('SP-')));
 assert.equal(parts.length,2);assert.equal(parts.reduce((s,o)=>s+o.items[0].qty,0),40);
 assert.equal(parts[0].created,merged.created);assert.equal(parts[0].due,merged.due);
 await page.getByRole('checkbox',{name:'选择 '+parts[0].id,exact:true}).check();
 await page.getByRole('button',{name:'创建发货计划',exact:true}).click();
 await page.getByRole('button',{name:'下一步',exact:true}).click();
 await page.locator('#weight').fill('0');
 await page.getByRole('button',{name:'下一步',exact:true}).click();
 assert.match(await page.locator('#wizardError').innerText(),/大于 0/);
 await page.locator('#weight').fill('12');
 await page.getByRole('button',{name:'下一步',exact:true}).click();
 assert.equal(await page.evaluate(()=>wizard.courier),'中通快递');
 await page.screenshot({path:'E:/cxy/09-设计与原型/计划发货管理-快递比价.png',fullPage:true});
 await page.getByRole('button',{name:'下一步',exact:true}).click();
 await page.getByRole('button',{name:'确认计划',exact:true}).click();
 let pid=await page.evaluate(()=>state.plans[0].id);
 await page.getByRole('button',{name:'模拟同步失败',exact:true}).click();
 await page.waitForTimeout(1100);
 assert.equal(await page.evaluate(()=>state.plans[0].sync),'failed');
 await page.getByRole('button',{name:'修复映射并重试',exact:true}).click();
 await page.waitForTimeout(1100);
 assert.equal(await page.evaluate(()=>state.plans[0].sync),'success');
 assert.equal(await page.evaluate(()=>state.plans.filter(p=>p.id===state.plans[0].id).length),1);
 await page.getByRole('button',{name:'模拟旺店通发货回传',exact:true}).click();
 assert.equal(await page.evaluate(()=>state.plans[0].shipped),true);
 assert.equal(await page.getByRole('button',{name:'取消计划',exact:true}).count(),0);
 await page.getByRole('button',{name:'关闭弹窗',exact:true}).click();
 await page.reload();assert.equal(await page.evaluate(()=>state.plans[0].id),pid);
 await page.getByRole('button',{name:'新建发货计划'}).click();
 await page.locator('#modalBody label').filter({hasText:'SO-005'}).locator('input').check();
 await page.getByRole('button',{name:'下一步',exact:true}).click();
 await page.getByRole('button',{name:'保存草稿',exact:true}).click();
 assert.equal(await page.evaluate(()=>state.plans[0].status),'draft');
 await page.getByRole('button',{name:'继续编辑',exact:true}).first().click();
 await page.getByRole('button',{name:'下一步',exact:true}).click();
 assert.equal(await page.evaluate(()=>quotes().filter(q=>q.ok).length),0);
 await page.getByRole('button',{name:'下一步',exact:true}).click();
 assert.match(await page.locator('#wizardError').innerText(),/原因/);
 await page.locator('#reason').fill('客户确认延迟收货');
 await page.getByRole('button',{name:'下一步',exact:true}).click();
 assert.match(await page.locator('#wizardError').innerText(),/风险/);
 await page.getByRole('checkbox',{name:'已知可能晚到'}).check();
 await page.getByRole('button',{name:'下一步',exact:true}).click();
 await page.getByRole('button',{name:'确认计划',exact:true}).click();
 await page.getByRole('button',{name:'取消计划',exact:true}).click();
 await page.getByRole('button',{name:'确认取消',exact:true}).click();
 assert.match(await page.locator('#cancelError').innerText(),/原因/);
 await page.locator('#cancelReason').fill('客户调整计划');
 await page.getByRole('button',{name:'确认取消',exact:true}).click();
 assert.equal(await page.evaluate(()=>state.orders.find(o=>o.id==='SO-005').status),'ready');
 await page.getByRole('button',{name:'订单拆合单'}).click();
 await page.getByRole('checkbox',{name:'选择 SO-004',exact:true}).check();
 await page.getByRole('checkbox',{name:'选择 SO-005',exact:true}).check();
 await page.getByRole('button',{name:'合并订单',exact:true}).click();
 assert.match(await page.locator('#toast').innerText(),/无法合单/);
 await page.getByRole('button',{name:'物流与预警配置'}).click();
 await page.locator('#cfg-warn').fill('24');
 await page.getByRole('button',{name:'保存配置',exact:true}).click();
 assert.equal(await page.evaluate(()=>state.config.warn),24);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'计划发货管理',exact:true}).click();
 await page.screenshot({path:'E:/cxy/09-设计与原型/计划发货管理-手机预览.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);console.log('PASS: 数量守恒、来源时间、表单校验、低价推荐、同步失败与重试、发货回传、草稿恢复、晚到确认、取消释放、合单限制、配置保存、持久化、移动端宽度；无浏览器脚本错误。');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
